#!/bin/bash

PIPE_FAIL(){
set -o pipefail
}

MAIN_PKGS() {
sudo xbps-install -Syu -u xbps && sudo xbps-install -Syu
sudo xbps-install -Syu xfce4 xfce4-whiskermenu-plugin xfce4-pulseaudio-plugin pavucontrol pulseaudio xorg-minimal xorg-fonts gvfs file-roller vim papirus-icon-theme arc-theme evince celluloid torbrowser-launcher lxdm
}

START_SERVICES(){
sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/lxdm /var/service
sudo ln -s /etc/sv/polkitd /var/service
sudo ln -s /etc/sv/rtkit /var/service
sudo ln -s /etc/sv/elogind /var/service
sudo sed -i 's|# session=/usr/bin/startlxde|session=/usr/bin/startxfce4|g' /etc/lxdm/lxdm.conf
sudo sed -i 's|# autologin=dgod|autologin=user|g' /etc/lxdm/lxdm.conf
cp -r ENV/. /$HOME/
}

REBOOT_CASE() { 
clear && /bin/echo -e '\n\n' "\e[1;32mREBOOTING NOW......\e[0m"
sleep 1
clear && /bin/echo -e '\n\n' "\e[1;31mEXITING......\e[0m" 
sudo reboot
}

#runfunctions

PIPE_FAIL
MAIN_PKGS || MAIN_PKGS 
START_SERVICES
REBOOT_CASE
